"""SQLAlchemy ORM model: assessment_narratives table.

AI narratives are stored SEPARATELY from deterministic assessment data.
AI content must NEVER mutate deterministic assessment records.
"""

import uuid
from datetime import datetime, timezone
from typing import Optional

import sqlalchemy as sa
from sqlalchemy import String, DateTime, CheckConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.types import _JsonColumn

from app.database.database import Base


class AssessmentNarrative(Base):
    """Stores AI-generated forensic narrative for a completed assessment.

    Status values:
    - COMPLETED: AI narrative successfully generated by LLM provider.
    - FALLBACK: Deterministic synthesizer used (no live LLM available).
    - UNAVAILABLE: AI generation failed entirely; deterministic assessment unaffected.
    """

    __tablename__ = "assessment_narratives"
    __table_args__ = (
        CheckConstraint(
            "status IN ('COMPLETED', 'FALLBACK', 'UNAVAILABLE')",
            name="ck_narrative_status",
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    assessment_id: Mapped[str] = mapped_column(String(36), sa.ForeignKey("assessments.id"), nullable=False, index=True)
    narrative_version: Mapped[str] = mapped_column(String(16), nullable=False, default="1.0")
    provider: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    model: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    prompt_version: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    # Full EFSNarrativeResponse serialized as JSONB
    narrative_payload: Mapped[dict] = mapped_column(_JsonColumn, nullable=False, default=dict)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        default=lambda: datetime.now(timezone.utc),
    )
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="FALLBACK")

    assessment: Mapped["Assessment"] = relationship("Assessment", back_populates="narratives")  # noqa: F821

    def __repr__(self) -> str:
        return f"<AssessmentNarrative provider={self.provider} status={self.status}>"
