import { useEffect, useState } from 'react'
import { CheckCircleOutline, DeleteOutline, ErrorOutline, InboxOutlined, Refresh, Replay, WifiOff } from '@mui/icons-material'
import { Box, Button, Card, CardContent, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, Stack, Typography } from '@mui/material'

export type EmptyVariant = 'history' | 'reports' | 'watchlist' | 'analysis'
export type ErrorVariant = '404' | '500' | 'network'

const emptyCopy: Record<EmptyVariant, { title: string; description: string; button: string }> = {
  history: { title: 'No analysis history yet', description: 'Completed company analyses will appear here for quick access.', button: 'Start an analysis' },
  reports: { title: 'No reports available', description: 'Generate a report from an analysis to see it in your report library.', button: 'Analyze a company' },
  watchlist: { title: 'Your watchlist is empty', description: 'Add companies to track earnings quality and risk over time.', button: 'Add a company' },
  analysis: { title: 'No analysis selected', description: 'Choose a company and upload statements to begin your forensic review.', button: 'New analysis' },
}

export function EmptyState({ variant, onAction }: { variant: EmptyVariant; onAction?: () => void }) { const copy = emptyCopy[variant]; return <Card><CardContent sx={{ py: 8, textAlign: 'center' }}><Box sx={{ width: 64, height: 64, mx: 'auto', mb: 2, display: 'grid', placeItems: 'center', borderRadius: '50%', bgcolor: 'rgba(99,91,255,.08)', color: 'primary.main' }}><InboxOutlined fontSize="large" /></Box><Typography variant="h2">{copy.title}</Typography><Typography color="text.secondary" sx={{ maxWidth: 420, mx: 'auto', mt: 1 }}>{copy.description}</Typography><Button variant="contained" onClick={onAction} sx={{ mt: 3 }}>{copy.button}</Button></CardContent></Card> }

const errorCopy: Record<ErrorVariant, { title: string; message: string }> = { '404': { title: 'Page not found', message: 'The page you are looking for may have moved or no longer exists.' }, '500': { title: 'Something went wrong', message: 'Our application encountered an unexpected error. Please try again.' }, network: { title: 'Connection unavailable', message: 'We could not reach the service. Check your connection and try again.' } }
export function ErrorState({ variant, onRetry }: { variant: ErrorVariant; onRetry?: () => void }) { const copy = errorCopy[variant]; return <Card><CardContent sx={{ py: 8, textAlign: 'center' }}><Box sx={{ width: 64, height: 64, mx: 'auto', mb: 2, display: 'grid', placeItems: 'center', borderRadius: '50%', bgcolor: 'rgba(217,79,92,.08)', color: 'error.main' }}>{variant === 'network' ? <WifiOff fontSize="large" /> : <ErrorOutline fontSize="large" />}</Box><Typography variant="h2">{copy.title}</Typography><Typography color="text.secondary" sx={{ maxWidth: 420, mx: 'auto', mt: 1 }}>{copy.message}</Typography><Stack direction="row" justifyContent="center" spacing={1} sx={{ mt: 3 }}><Button variant="outlined" href="/">Go home</Button><Button variant="contained" onClick={onRetry} startIcon={<Refresh />}>Retry</Button></Stack></CardContent></Card> }

export function LoadingState({ label = 'Preparing your workspace' }: { label?: string }) { const [progress, setProgress] = useState(0); useEffect(() => { const timer = window.setInterval(() => setProgress((value) => Math.min(value + 3, 100)), 100); return () => window.clearInterval(timer) }, []); const checks = ['Loading Dashboard', 'Analyzing Statements', 'Generating AI Report', 'Preparing Results']; return <Card><CardContent sx={{ py: 8, textAlign: 'center' }}><CircularProgress variant="determinate" value={progress} size={72} thickness={3} /><Typography variant="h2" sx={{ mt: 3 }}>{label}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>EarningsGuard™ AI is preparing your workspace.</Typography><Box sx={{ maxWidth: 420, mx: 'auto', mt: 3 }}><Stack spacing={1.25} textAlign="left">{checks.map((check, index) => <Stack direction="row" alignItems="center" spacing={1} key={check} color={progress > (index + 1) * 25 ? 'success.main' : 'text.secondary'}>{progress > (index + 1) * 25 ? <CheckCircleOutline fontSize="small" /> : <Replay fontSize="small" />}<Typography variant="body2">{check}</Typography></Stack>)}</Stack></Box></CardContent></Card> }

export function SuccessDialog({ open, title, message, onClose }: { open: boolean; title: string; message: string; onClose: () => void }) { return <Dialog open={open} onClose={onClose} maxWidth="xs" fullWidth><DialogContent sx={{ textAlign: 'center', py: 4 }}><CheckCircleOutline color="success" sx={{ fontSize: 48 }} /><Typography variant="h2" sx={{ mt: 1.5 }}>{title}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{message}</Typography></DialogContent><DialogActions sx={{ justifyContent: 'center', pb: 2 }}><Button variant="contained" onClick={onClose}>Done</Button></DialogActions></Dialog> }

export function ConfirmDialog({ open, title, message, onCancel, onConfirm }: { open: boolean; title: string; message: string; onCancel: () => void; onConfirm: () => void }) { return <Dialog open={open} onClose={onCancel} maxWidth="xs" fullWidth><DialogTitle>{title}</DialogTitle><DialogContent><Typography color="text.secondary">{message}</Typography></DialogContent><DialogActions sx={{ p: 2 }}><Button onClick={onCancel}>Cancel</Button><Button color="error" variant="contained" startIcon={<DeleteOutline />} onClick={onConfirm}>Confirm</Button></DialogActions></Dialog> }
