import { AutoAwesomeOutlined, AutoFixHighOutlined } from '@mui/icons-material'
import { Box, Button, Card, CardContent, FormControl, MenuItem, Select, Stack, Typography } from '@mui/material'
import type { FieldMapping } from '../types'
import { standardFields } from '../data'

interface MappingTableProps { mappings: FieldMapping[]; onChange: (index: number, value: string) => void; onAutoMap: () => void }

export function MappingTable({ mappings, onChange, onAutoMap }: MappingTableProps) {
  return <Card><CardContent sx={{ p: { xs: 2, md: 3 }, '&:last-child': { pb: { xs: 2, md: 3 } } }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1.5} sx={{ mb: 2.5 }}><Box><Typography variant="h3">Map detected columns</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Review our suggestions and map each column to a standard field.</Typography></Box><Stack direction="row" spacing={1}><Button size="small" variant="outlined" startIcon={<AutoFixHighOutlined />} onClick={onAutoMap}>Auto map</Button><Button size="small" variant="outlined" startIcon={<AutoAwesomeOutlined />} onClick={onAutoMap}>AI suggest mapping</Button></Stack></Stack><Box sx={{ display: { xs: 'none', sm: 'grid' }, gridTemplateColumns: '1fr 1fr', gap: 2, px: 1.5, py: 1, bgcolor: '#f7f8fc', borderRadius: 1.5 }}><Typography variant="caption" color="text.secondary">DETECTED COLUMN</Typography><Typography variant="caption" color="text.secondary">MAPPED STANDARD FIELD</Typography></Box><Stack spacing={1}>{mappings.map((mapping, index) => <Box key={mapping.detectedColumn} sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: '1fr 1fr' }, gap: { xs: 1, sm: 2 }, alignItems: 'center', px: 1.5, py: 1.25, borderBottom: 1, borderColor: 'divider' }}><Typography fontSize=".82rem" fontWeight={650}>{mapping.detectedColumn}</Typography><FormControl size="small" fullWidth><Select value={mapping.standardField} onChange={(event) => onChange(index, event.target.value)} displayEmpty aria-label={`Map ${mapping.detectedColumn}`}><MenuItem value=""><em>Not mapped</em></MenuItem>{standardFields.map((field) => <MenuItem key={field} value={field}>{field}</MenuItem>)}</Select></FormControl></Box>)}</Stack></CardContent></Card>
}
