import { DeleteOutline, FilterList, PlayArrow, Search, VisibilityOutlined } from '@mui/icons-material'
import { Box, Button, Card, CardContent, Chip, IconButton, InputAdornment, Pagination, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { useState } from 'react'
import { ConfirmDialog, EmptyState } from '../components/feedback/FeedbackComponents'

interface HistoryItem { id: number; company: string; ticker: string; date: string; score: number; rating: string; risk: string; status: string }
const initialRows: HistoryItem[] = [{ id: 1, company: 'Infosys Ltd.', ticker: 'INFY', date: '22 Jul 2026', score: 84, rating: 'AA', risk: 'Low', status: 'Completed' }, { id: 2, company: 'TCS', ticker: 'TCS', date: '18 Jul 2026', score: 81, rating: 'AA', risk: 'Low', status: 'Completed' }, { id: 3, company: 'HCL Technologies', ticker: 'HCLTECH', date: '12 Jul 2026', score: 77, rating: 'A', risk: 'Moderate', status: 'Completed' }, { id: 4, company: 'Wipro', ticker: 'WIPRO', date: '08 Jul 2026', score: 73, rating: 'A', risk: 'Moderate', status: 'Completed' }, { id: 5, company: 'Reliance Industries', ticker: 'RELIANCE', date: '03 Jul 2026', score: 78, rating: 'A', risk: 'Low', status: 'Completed' }]
export function History() { const [rows, setRows] = useState(initialRows); const [query, setQuery] = useState(''); const [deleteId, setDeleteId] = useState<number | null>(null); const filtered = rows.filter((row) => `${row.company} ${row.ticker}`.toLowerCase().includes(query.toLowerCase())); return <Page title="Analysis history" subtitle="Review, revisit, and rerun your previous forensic analyses."><Card><CardContent sx={{ p: 0 }}><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" spacing={1.5} sx={{ p: 2.5 }}><TextField size="small" placeholder="Search analyses" value={query} onChange={(event) => setQuery(event.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><Search fontSize="small" /></InputAdornment> }} /><Button variant="outlined" startIcon={<FilterList />}>Filter</Button></Stack>{filtered.length ? <><TableContainer><Table size="small"><TableHead><TableRow>{['COMPANY', 'TICKER', 'DATE', 'EFS SCORE', 'RATING', 'RISK', 'STATUS', 'ACTIONS'].map((head) => <TableCell key={head}>{head}</TableCell>)}</TableRow></TableHead><TableBody>{filtered.map((row) => <TableRow key={row.id}><TableCell sx={{ fontWeight: 700 }}>{row.company}</TableCell><TableCell>{row.ticker}</TableCell><TableCell>{row.date}</TableCell><TableCell sx={{ fontWeight: 800 }}>{row.score}</TableCell><TableCell><Chip label={row.rating} color="success" size="small" variant="outlined" /></TableCell><TableCell><Chip label={row.risk} color={row.risk === 'Low' ? 'success' : 'warning'} size="small" variant="outlined" /></TableCell><TableCell><Chip label={row.status} color="success" size="small" /></TableCell><TableCell><Stack direction="row"><IconButton size="small" aria-label="View"><VisibilityOutlined fontSize="small" /></IconButton><IconButton size="small" aria-label="Re-run"><PlayArrow fontSize="small" /></IconButton><IconButton size="small" color="error" aria-label="Delete" onClick={() => setDeleteId(row.id)}><DeleteOutline fontSize="small" /></IconButton></Stack></TableCell></TableRow>)}</TableBody></Table></TableContainer><Stack alignItems="center" sx={{ p: 2 }}><Pagination count={3} page={1} /></Stack></> : <Box sx={{ p: 2 }}><EmptyState variant="history" /></Box>}</CardContent></Card><ConfirmDialog open={deleteId !== null} title="Delete analysis?" message="This analysis will be removed from your history." onCancel={() => setDeleteId(null)} onConfirm={() => { setRows((current) => current.filter((row) => row.id !== deleteId)); setDeleteId(null) }} /></Page> }
function Page({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <Box sx={{ p: { xs: 2, md: 4 }, maxWidth: 1400, mx: 'auto' }}><Typography variant="h1">{title}</Typography><Typography color="text.secondary" sx={{ mt: .5, mb: 3.5 }}>{subtitle}</Typography>{children}</Box> }
