import { useState } from 'react'
import { AutoAwesomeOutlined, CheckCircleOutline, FileDownloadOutlined, SaveOutlined, SearchOutlined } from '@mui/icons-material'
import { Autocomplete, Box, Button, Card, CardContent, Chip, InputAdornment, LinearProgress, Stack, Table, TableBody, TableCell, TableContainer, TableHead, TableRow, TextField, Typography } from '@mui/material'
import { PolarAngleAxis, PolarGrid, PolarRadiusAxis, Radar, RadarChart, ResponsiveContainer, Tooltip, Legend, BarChart, Bar, CartesianGrid, XAxis, YAxis } from 'recharts'
import { companies, pillarNames, type CompanyComparison } from '../data'

const chartColors = ['#635bff', '#0f9f72', '#d98b10', '#d94f5c', '#0284c7']
const tone = (score: number) => score >= 80 ? 'success.main' : score >= 70 ? 'warning.main' : 'error.main'
const chipColor = (value: string) => value === 'Low' || value === 'Strong' || value === 'AA' ? 'success' : value === 'Moderate' || value === 'Stable' || value === 'A' ? 'warning' : 'error'

export function CompanySelector({ selected, onChange }: { selected: CompanyComparison[]; onChange: (value: CompanyComparison[]) => void }) {
  return <Card><CardContent sx={{ p: { xs: 2.5, md: 3 } }}><Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" spacing={2} alignItems={{ md: 'center' }}><Box><Typography variant="h3">Select companies to compare</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Choose up to five companies for a side-by-side forensic review.</Typography></Box><Autocomplete multiple limitTags={2} options={companies} value={selected} onChange={(_, value) => onChange(value.slice(0, 5))} getOptionLabel={(option) => `${option.name} (${option.ticker})`} isOptionEqualToValue={(option, value) => option.id === value.id} sx={{ minWidth: { md: 460 }, maxWidth: '100%' }} renderInput={(params) => <TextField {...params} label="Search and add companies" placeholder={selected.length >= 5 ? '' : 'Search companies'} InputProps={{ ...params.InputProps, startAdornment: <><InputAdornment position="start"><SearchOutlined fontSize="small" /></InputAdornment>{params.InputProps.startAdornment}</> }} />} renderTags={(value, getTagProps) => value.map((option, index) => <Chip {...getTagProps({ index })} key={option.id} label={option.shortName} size="small" color="primary" variant="outlined" />)} /></Stack><Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: 1.25 }}>{selected.length}/5 companies selected</Typography></CardContent></Card>
}

export function SummaryTable({ selected }: { selected: CompanyComparison[] }) { return <Card><CardContent sx={{ p: 0 }}><Box sx={{ p: 2.5, pb: 1.5 }}><Typography variant="h3">Comparison summary</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>A high-level view of forensic earnings quality.</Typography></Box><TableContainer><Table size="small"><TableHead><TableRow>{['COMPANY', 'EFS SCORE', 'RATING', 'MANIPULATION RISK', 'FINANCIAL HEALTH', 'CONFIDENCE'].map((head) => <TableCell key={head}>{head}</TableCell>)}</TableRow></TableHead><TableBody>{selected.map((company) => <TableRow key={company.id}><TableCell><Typography fontWeight={750} fontSize=".82rem">{company.name}</Typography><Typography variant="caption" color="text.secondary">{company.ticker}</Typography></TableCell><TableCell><Stack direction="row" alignItems="center" spacing={1}><Typography fontWeight={800}>{company.score}</Typography><LinearProgress variant="determinate" value={company.score} sx={{ width: 60, height: 5, borderRadius: 4, '& .MuiLinearProgress-bar': { bgcolor: tone(company.score) } }} /></Stack></TableCell><TableCell><StatusChip label={company.rating} /></TableCell><TableCell><StatusChip label={company.risk} /></TableCell><TableCell><StatusChip label={company.health} /></TableCell><TableCell sx={{ fontWeight: 700 }}>{company.confidence}%</TableCell></TableRow>)}</TableBody></Table></TableContainer></CardContent></Card> }
function StatusChip({ label }: { label: string }) { return <Chip label={label} size="small" color={chipColor(label)} variant="outlined" /> }

export function RadarComparison({ selected }: { selected: CompanyComparison[] }) { const data = pillarNames.map((pillar, index) => ({ pillar: pillar.replace('Financial Statement Quality', 'Statement Quality').replace('Balance Sheet Integrity', 'Balance Sheet'), ...Object.fromEntries(selected.map((company) => [company.id, company.pillars[index]])) })); return <Card sx={{ height: '100%' }}><CardContent sx={{ p: 2.5 }}><Typography variant="h3">EFS™ pillar comparison</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Seven-dimensional forensic quality profile</Typography><Box sx={{ height: 360, mt: 1 }}><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} margin={{ top: 10, right: 20, bottom: 10, left: 20 }}><PolarGrid stroke="#e7eaf0" /><PolarAngleAxis dataKey="pillar" tick={{ fill: '#697386', fontSize: 10 }} /><PolarRadiusAxis domain={[0, 100]} tick={false} axisLine={false} /><Tooltip /><Legend wrapperStyle={{ fontSize: 11 }} />{selected.map((company, index) => <Radar key={company.id} name={company.shortName} dataKey={company.id} stroke={chartColors[index]} fill={chartColors[index]} fillOpacity={.08} strokeWidth={2} />)}</RadarChart></ResponsiveContainer></Box></CardContent></Card> }

export function ScoreBarChart({ selected }: { selected: CompanyComparison[] }) { return <Card sx={{ height: '100%' }}><CardContent sx={{ p: 2.5 }}><Typography variant="h3">Overall EFS™ score</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Relative ranking across selected companies</Typography><Box sx={{ height: 360, mt: 2 }}><ResponsiveContainer width="100%" height="100%"><BarChart data={selected.map((company) => ({ name: company.shortName, score: company.score }))} layout="vertical" margin={{ top: 10, right: 20, left: 20, bottom: 0 }}><CartesianGrid horizontal={false} stroke="#e7eaf0" /><XAxis type="number" domain={[0, 100]} hide /><YAxis type="category" dataKey="name" width={90} tick={{ fill: '#697386', fontSize: 11 }} axisLine={false} tickLine={false} /><Tooltip /><Bar dataKey="score" fill="#635bff" radius={[0, 5, 5, 0]} barSize={22} label={{ position: 'right', fill: '#172033', fontSize: 12, fontWeight: 700 }} /></BarChart></ResponsiveContainer></Box></CardContent></Card> }

export function HeatmapTable({ selected }: { selected: CompanyComparison[] }) { return <Card><CardContent sx={{ p: 0 }}><Box sx={{ p: 2.5, pb: 1.5 }}><Typography variant="h3">Pillar heatmap</Typography><Typography variant="body2" color="text.secondary" sx={{ mt: .5 }}>Green indicates strength; amber indicates watch areas.</Typography></Box><TableContainer><Table size="small"><TableHead><TableRow><TableCell>PILLAR</TableCell>{selected.map((company) => <TableCell align="center" key={company.id}>{company.shortName}</TableCell>)}</TableRow></TableHead><TableBody>{pillarNames.map((pillar, index) => <TableRow key={pillar}><TableCell sx={{ fontWeight: 650, whiteSpace: 'nowrap' }}>{pillar}</TableCell>{selected.map((company) => { const score = company.pillars[index]; return <TableCell align="center" key={company.id}><Box sx={{ display: 'inline-flex', minWidth: 48, justifyContent: 'center', py: .6, px: .8, borderRadius: 1, bgcolor: score >= 80 ? 'rgba(15,159,114,.12)' : score >= 70 ? 'rgba(217,139,16,.14)' : 'rgba(217,79,92,.12)', color: tone(score), fontWeight: 800, fontSize: '.8rem' }}>{score}</Box></TableCell> })}</TableRow>)}</TableBody></Table></TableContainer></CardContent></Card> }

export function RankingPanel({ selected }: { selected: CompanyComparison[] }) { const ranking = [...selected].sort((a, b) => b.score - a.score); return <Card><CardContent sx={{ p: 2.5 }}><Typography variant="h3">Ranking</Typography><Stack spacing={1.25} sx={{ mt: 2 }}>{ranking.map((company, index) => <Stack direction="row" alignItems="center" spacing={1.5} key={company.id} sx={{ p: 1.25, bgcolor: index === 0 ? 'rgba(99,91,255,.06)' : '#f7f8fc', borderRadius: 1.5 }}><Typography sx={{ width: 28, color: index === 0 ? 'primary.main' : 'text.secondary', fontWeight: 800 }}>#{index + 1}</Typography><Box sx={{ flex: 1 }}><Typography fontWeight={750} fontSize=".82rem">{company.shortName}</Typography><Typography variant="caption" color="text.secondary">{company.ticker}</Typography></Box><Typography fontWeight={800}>{company.score}</Typography><StatusChip label={company.rating} /></Stack>)}</Stack></CardContent></Card> }

export function InsightsPanel() { return <Card><CardContent sx={{ p: 2.5 }}><Stack direction="row" spacing={1} alignItems="center"><AutoAwesomeOutlined color="primary" fontSize="small" /><Typography variant="h3">AI insights</Typography></Stack><Stack spacing={1.5} sx={{ mt: 2 }}>{['Infosys has the strongest governance score in the selected group.', 'TCS has superior cash flow integrity at 92.', 'HCL shows elevated accrual risk and should be monitored closely.'].map((insight) => <Stack direction="row" spacing={1} key={insight}><CheckCircleOutline sx={{ fontSize: 17, color: 'primary.main', mt: .25 }} /><Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.6 }}>{insight}</Typography></Stack>)}</Stack></CardContent></Card> }

export function ComparisonActions() { const [saved, setSaved] = useState(false); return <Stack direction={{ xs: 'column', sm: 'row' }} spacing={1.25}><Button variant="outlined" startIcon={<FileDownloadOutlined />}>Export comparison PDF</Button><Button variant="outlined" startIcon={<FileDownloadOutlined />}>Export Excel</Button><Button variant={saved ? 'contained' : 'outlined'} startIcon={<SaveOutlined />} onClick={() => setSaved(true)}>{saved ? 'Comparison saved' : 'Save comparison'}</Button></Stack> }
